apiVersion: v1
kind: Secret
metadata:
  name: chenna-live-runner-secrets
type: Opaque
stringData:
  TOKENS_ENCRYPTION_KEY: "D9mduJX0wa7fLuqhH9oTsQK43Pg3lh36U4+eNzLL45o="
  ADMIN_SHARED_SECRET: "zvqKld+pX2mAuuEKh+zydmmfhGTxjfVB"
