const fs = require('fs');
const path = require('path');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const CACHE_DIR_30M = path.join(__dirname, '../cache/30minute');

function load30mCache(symbol) {
    const cleanKey = symbol.replace(/[^a-zA-Z0-9_-]/g, '_');
    const p = path.join(CACHE_DIR_30M, `${cleanKey}_master.json`);
    if (!fs.existsSync(p)) return null;
    try {
        const raw = JSON.parse(fs.readFileSync(p, 'utf8'));
        const byDay = {};
        for (const c of raw) {
            const parts = String(c.timestamp || c.date).split('T');
            const d = parts[0];
            const t = parts[1].substring(0, 8);
            if (!byDay[d]) byDay[d] = [];
            byDay[d].push({ ...c, timeStr: t });
        }
        return byDay;
    } catch (e) { return null; }
}

async function main() {
    console.log("=== RIGOROUS RETEST FUNNEL VERIFICATION ===");

    // VERIFICATION 1: DATASET EXACT SIZE
    const ibCats = await prisma.stockCategory.findMany({
        where: { category: { key: 'INTRADAY_BOOST' } },
        include: { stock: true }
    });

    const dateMap = {};
    const allSymbolsSet = new Set();

    for (const r of ibCats) {
        if (!r.addedDate || !r.stock) continue;
        const dt = r.addedDate.toISOString().split('T')[0];
        const sym = r.stock.symbol;
        allSymbolsSet.add(sym);
        if (!dateMap[dt]) dateMap[dt] = [];
        dateMap[dt].push(sym);
    }

    const sortedDates = Object.keys(dateMap).sort();

    console.log(`\n--- VERIFICATION 1: DATASET SIZE ---`);
    console.log(`Total unique dates in IB category: ${sortedDates.length}`);
    console.log(`Total unique symbols ever in IB: ${allSymbolsSet.size}`);

    let totalTargetStockDays = 0;
    let actualCachedStockDays = 0;

    const fileCache30m = {};
    for (const sym of Array.from(allSymbolsSet)) {
        const c30 = load30mCache(sym);
        if (c30) fileCache30m[sym] = c30;
    }

    // We strictly iterate ONLY the dates and symbols that appeared IN THAT SCANNED DATE.
    for (const day of sortedDates) {
        for (const sym of dateMap[day]) {
            totalTargetStockDays++;
            if (fileCache30m[sym] && fileCache30m[sym][day] && fileCache30m[sym][day].length >= 5) {
                actualCachedStockDays++;
            }
        }
    }

    console.log(`Total Stock-day combinations generated by IB scanner: ${totalTargetStockDays}`);
    console.log(`Total Stock-day combinations ACTUALLY CACHED & PROCESSABLE: ${actualCachedStockDays}`);
    console.log(`(Explanation: The 27k run executed blindly over all files in the cache dir for all days. For reality, we MUST constrain to the ${actualCachedStockDays} samples exactly matching the IB signal calendar).`);

    // Run the constrained study
    let totalBreakouts = 0;
    let totalRetests = 0;
    let retestHeld = 0;
    let retestFailed = 0;
    let noRetest = 0;

    let totalHeldT1Hits = 0;
    let totalHeldT2Hits = 0;
    let totalHeldStops = 0; // Total stops hit eventually
    let intraCandleStopRuns = 0; // Specific stops pierced *during* the retest 30m candle
    let totalHeldDrifts = 0;
    let totalHeldWinR = 0;
    let totalHeldDriftR = 0;

    const diverseExamples = [];
    const usedSyms = new Set();

    const auditDay = '2026-02-19'; // Use Feb 19 for Verification 4
    const auditLog = [];

    for (const day of sortedDates) {
        const symbols = dateMap[day];

        for (const sym of symbols) {
            const data30 = fileCache30m[sym];
            if (!data30 || !data30[day]) {
                if (day === auditDay) auditLog.push({ sym, or: 'No cache data', bo: 'N/A', ret: 'N/A', held: 'N/A', res: 'N/A' });
                continue;
            }
            const candles = data30[day];
            if (candles.length < 5) {
                if (day === auditDay) auditLog.push({ sym, or: 'Not enough candles', bo: 'N/A', ret: 'N/A', held: 'N/A', res: 'N/A' });
                continue;
            }

            const c1 = candles[0];
            const orh = parseFloat(c1.high), orl = parseFloat(c1.low), orRange = orh - orl;
            if (orRange === 0) {
                if (day === auditDay) auditLog.push({ sym, or: 'Zero range', bo: 'N/A', ret: 'N/A', held: 'N/A', res: 'N/A' });
                continue;
            }

            let bIdx = -1, sType = null, boPrice = 0;
            for (let i = 1; i < candles.length && i <= 8; i++) { // <= 13:30
                const c = parseFloat(candles[i].close);
                if (c > orh) { bIdx = i; sType = 'LONG'; boPrice = c; break; }
                else if (c < orl) { bIdx = i; sType = 'SHORT'; boPrice = c; break; }
            }

            if (bIdx === -1) {
                if (day === auditDay) auditLog.push({ sym, or: `${orh}-${orl}`, bo: 'NO', ret: 'NO', held: 'NO', res: 'No Breakout' });
                continue;
            }

            totalBreakouts++;

            const bCandle = candles[bIdx];
            const baseStop = sType === 'LONG' ? parseFloat(bCandle.low) : parseFloat(bCandle.high);
            const risk = Math.max(Math.abs(boPrice - baseStop), boPrice * 0.005);

            let touchedOR = false;
            let retestBounce = false;
            let retestFail = false;
            let touchedIdx = -1;
            let entryPrice = 0;

            // VERIFICATION 3 Tracker
            let piercedStopDuringRetestCandle = false;

            for (let i = bIdx + 1; i < candles.length; i++) {
                const c = candles[i];
                const ch = parseFloat(c.high);
                const cl = parseFloat(c.low);
                const cc = parseFloat(c.close);

                if (sType === 'LONG') {
                    if (!touchedOR && cl <= orh) {
                        touchedOR = true; touchedIdx = i; entryPrice = orh;
                        // Checking intra-candle stop
                        if (cl <= baseStop) piercedStopDuringRetestCandle = true;
                    }
                    if (touchedOR) {
                        if (cc < orh) { retestFail = true; break; }
                        else if (ch > entryPrice + (risk * 0.5)) { retestBounce = true; }
                    }
                } else {
                    if (!touchedOR && ch >= orl) {
                        touchedOR = true; touchedIdx = i; entryPrice = orl;
                        // Checking intra-candle stop
                        if (ch >= baseStop) piercedStopDuringRetestCandle = true;
                    }
                    if (touchedOR) {
                        if (cc > orl) { retestFail = true; break; }
                        else if (cl < entryPrice - (risk * 0.5)) { retestBounce = true; }
                    }
                }
            }

            if (touchedOR) {
                totalRetests++;

                if (piercedStopDuringRetestCandle) {
                    // Intra-candle stop hit. We cannot count this as a HELD trade.
                    intraCandleStopRuns++;
                    retestFail = true;
                    retestBounce = false;
                }

                if (retestFail) {
                    retestFailed++;
                    if (day === auditDay) auditLog.push({ sym, or: `${orh}-${orl}`, bo: 'YES', ret: 'YES', held: 'NO (Failed/IntraStop)', res: 'No Trade' });
                } else if (retestBounce) {
                    retestHeld++;

                    const t1 = sType === 'LONG' ? entryPrice + risk : entryPrice - risk;
                    const t2 = sType === 'LONG' ? entryPrice + (risk * 2) : entryPrice - (risk * 2);

                    let execT1 = false, execT2 = false, execStop = false, finalExecR = null;

                    for (let j = touchedIdx; j < candles.length; j++) {
                        const exc = candles[j];
                        const eh = parseFloat(exc.high), el = parseFloat(exc.low);

                        if (sType === 'LONG') {
                            if (el < baseStop) { execStop = true; finalExecR = -1; break; }
                            if (!execT1 && eh >= t1) execT1 = true;
                            if (eh >= t2) { execT2 = true; execT1 = true; finalExecR = 2; break; }
                        } else {
                            if (eh > baseStop) { execStop = true; finalExecR = -1; break; }
                            if (!execT1 && el <= t1) execT1 = true;
                            if (el <= t2) { execT2 = true; execT1 = true; finalExecR = 2; break; }
                        }
                    }

                    if (finalExecR === null) {
                        const eod = parseFloat(candles[candles.length - 1].close);
                        if (sType === 'LONG') finalExecR = (eod - entryPrice) / risk;
                        else finalExecR = (entryPrice - eod) / risk;
                        if (execT1) finalExecR = 1.0;
                    }

                    if (execT1) { totalHeldT1Hits++; totalHeldWinR += finalExecR > 0 ? finalExecR : 1.0; }
                    if (execT2) totalHeldT2Hits++;
                    if (execStop) { totalHeldStops++; }
                    if (!execT1 && !execStop) { totalHeldDrifts++; totalHeldDriftR += finalExecR; }

                    let resStr = execT1 ? 'WIN' : (execStop ? 'LOSS' : 'DRIFT');
                    if (day === auditDay) auditLog.push({ sym, or: `${orh}-${orl}`, bo: 'YES', ret: 'YES', held: 'YES', res: resStr });

                    if (diverseExamples.length < 10 && !usedSyms.has(sym)) {
                        usedSyms.add(sym);
                        diverseExamples.push({ sym, day, sType, orh, orl, bcTime: candles[bIdx].timeStr, rcTime: candles[touchedIdx].timeStr, entryPrice, baseStop, t1, resStr });
                    }
                }
            } else {
                noRetest++;
                if (day === auditDay) auditLog.push({ sym, or: `${orh}-${orl}`, bo: 'YES', ret: 'NO', held: 'N/A', res: 'Missed move' });
            }
        }
    }

    console.log(`\n--- CONSTRAINED DATASET REALITY ---`);
    console.log(`Of the ${actualCachedStockDays} perfectly verified IB events:`);
    console.log(`Total 30m Breakouts: ${totalBreakouts}`);
    console.log(`  -> Retested the OR level: ${totalRetests} (${((totalRetests / totalBreakouts) * 100).toFixed(1)}%)`);
    console.log(`\n--- VERIFICATION 3: INTRA-CANDLE STOP RUNS ---`);
    console.log(`Retest candles where the 30-min High/Low pierced the Stop BEFORE closing: ${intraCandleStopRuns} out of ${totalRetests} retests (${((intraCandleStopRuns / totalRetests) * 100).toFixed(1)}%)`);
    console.log(`(These were stripped out of the 'HELD' pool, as they would have stopped out a live trader immediately).`);

    console.log(`\n--- STRIPPED DOWN FUNNEL RESULT ---`);
    console.log(`  -> Retest truly HELD (Bounced, no intra-candle stop run): ${retestHeld} (${((retestHeld / totalRetests) * 100).toFixed(1)}%)`);
    console.log(`      Average entries per IB DAY: ${(retestHeld / sortedDates.length).toFixed(1)} trades/day  (across 49 stocks)`);
    console.log(`      Win rate (T1 Hit): ${((totalHeldT1Hits / retestHeld) * 100).toFixed(1)}%`);
    console.log(`      Stop Rate: ${((totalHeldStops / retestHeld) * 100).toFixed(1)}%`);
    console.log(`      Drift Rate: ${((totalHeldDrifts / retestHeld) * 100).toFixed(1)}%`);

    const avgWinR = totalHeldT1Hits > 0 ? (totalHeldWinR / totalHeldT1Hits) : 0;
    const avgDriftR = totalHeldDrifts > 0 ? (totalHeldDriftR / totalHeldDrifts) : 0;
    const wr = retestHeld ? totalHeldT1Hits / retestHeld : 0;
    const sr = retestHeld ? totalHeldStops / retestHeld : 0;
    const dr = retestHeld ? totalHeldDrifts / retestHeld : 0;
    const ev = retestHeld ? ((wr * avgWinR) + (sr * -1) + (dr * avgDriftR)) : 0;

    console.log(`  EV per trade: ${ev > 0 ? '+' + ev.toFixed(3) : ev.toFixed(3)}R`);

    console.log(`\n--- VERIFICATION 2: DIVERSE EXAMPLES ---`);
    for (const ex of diverseExamples) {
        console.log(`Stock: ${ex.sym.padEnd(12)} | Date: ${ex.day} | OR: ${ex.orh}-${ex.orl}`);
        console.log(`  Breakout time: ${ex.bcTime} | Retest time: ${ex.rcTime}`);
        console.log(`  Entry: ${ex.entryPrice.toFixed(2)} | Stop: ${ex.baseStop.toFixed(2)} | T1: ${ex.t1.toFixed(2)} | Result: ${ex.resStr}\n`);
    }

    console.log(`\n--- VERIFICATION 4: SINGLE DAY AUDIT (${auditDay}) ---`);
    for (const a of auditLog) {
        if (a.or === 'No cache data' || a.or === 'Not enough candles') continue; // Hide the un-cached ones for clarity
        console.log(`${a.sym.padEnd(12)} | OR: ${a.or.padEnd(12)} | BO: ${a.bo.padEnd(4)} | Retest: ${a.ret.padEnd(4)} | Held: ${a.held.padEnd(20)} | Result: ${a.res}`);
    }

}

main().catch(console.error).finally(() => prisma.$disconnect());
