/**
 * AI Analysis Service
 * 
 * Handles saving and loading the JSON analysis files generated by the AI
 * (either manually pasted by the user during the Agent-as-Analyst phase,
 * or eventually automated via a GPT/Gemini API).
 */

const fs = require('fs').promises;
const path = require('path');
const { todayIST } = require('../utils/istUtils.cjs');

const DATA_DIR = path.join(__dirname, '../data/ai-analysis');

class AIAnalysisService {
    constructor() {
        this.init();
    }

    async init() {
        try {
            await fs.mkdir(DATA_DIR, { recursive: true });
        } catch (e) {
            console.error('[AIAnalysisService] Could not create data directory:', e);
        }
    }

    /**
     * Get path for a specific date's analysis file
     * @param {string} dateStr YYYY-MM-DD
     */
    getFilePath(dateStr) {
        return path.join(DATA_DIR, `${dateStr}.json`);
    }

    /**
     * Save AI analysis JSON for a specific date
     * @param {string} dateStr YYYY-MM-DD
     * @param {object} analysisData The parsed JSON from the AI
     */
    async saveAnalysis(dateStr, analysisData) {
        if (!dateStr) dateStr = todayIST();

        const filePath = this.getFilePath(dateStr);

        // Add metadata (preserve caller-provided metadata if present)
        const payload = {
            ...analysisData,
            _metadata: analysisData._metadata || {
                savedAt: new Date().toISOString(),
                source: 'Agent-as-Analyst (Manual)',
                version: '1.0'
            }
        };

        try {
            await fs.writeFile(filePath, JSON.stringify(payload, null, 2), 'utf-8');
            console.log(`[AIAnalysisService] Saved analysis for ${dateStr} to ${filePath}`);
            return true;
        } catch (e) {
            console.error(`[AIAnalysisService] Failed to save analysis for ${dateStr}:`, e);
            throw e;
        }
    }

    /**
     * Retrieve AI analysis for a specific date
     * @param {string} dateStr YYYY-MM-DD
     * @returns {object|null} The analysis data or null if not found
     */
    async getAnalysis(dateStr) {
        if (!dateStr) dateStr = todayIST();
        const filePath = this.getFilePath(dateStr);

        try {
            // Check if file exists
            await fs.access(filePath);
            const data = await fs.readFile(filePath, 'utf-8');
            return JSON.parse(data);
        } catch (e) {
            if (e.code === 'ENOENT') {
                return null; // No analysis for this date
            }
            console.error(`[AIAnalysisService] Failed to read analysis for ${dateStr}:`, e);
            return null;
        }
    }
}

module.exports = new AIAnalysisService();
