#!/usr/bin/env node
// Strategy Workbench compiler
// Supports two modes:
// - JSON config -> normalized JSON (out ends with .json)
// - Text/JS workbench code -> runnable JS module exporting { onCandle, onStart, onStop, params } (out ends with .js)
const fs = require('fs');
const path = require('path');

function usage(){
  console.log('Usage:');
  console.log('  node tools/compile_strategy.cjs --input tmp/strategy_text.txt --out tmp/v1_compiled.js');
  console.log('  node tools/compile_strategy.cjs --in strategy.json --out backend/strategy/output/compiled.json');
}
function readJson(p){ try { return JSON.parse(fs.readFileSync(p,'utf8')); } catch (e) { return null; } }

function normalize(cfg){
  const out = { N: 3, volumeFactor: 0.9, atrStop: 1.0, targetR: 1.2, qty: 100 };
  if (cfg && typeof cfg === 'object') {
    for (const k of Object.keys(out)) { if (typeof cfg[k] === 'number') out[k] = cfg[k]; }
  }
  return out;
}

function wrapToModule(src){
  // If the source already exports a module, pass through after ensuring required keys
  const needsWrapper = !/module\.exports/.test(src);
  if (!needsWrapper) {
    // append fallback exports if missing
    const pieces = [];
    if (!/onStart\s*[:=]/.test(src) && !/onStart\s*\(/.test(src)) pieces.push('exports.onStart = function(){};');
    if (!/onStop\s*[:=]/.test(src) && !/onStop\s*\(/.test(src)) pieces.push('exports.onStop = function(){};');
    if (!/onCandle\s*[:=]/.test(src) && !/onCandle\s*\(/.test(src)) pieces.push('exports.onCandle = function(c){};');
    if (!/params\s*[:=]/.test(src)) pieces.push('exports.params = { N:2, volumeFactor:0.8, atrStop:0.9, targetR:1.1, qty:100 };');
    return src + '\n' + pieces.join('\n') + '\n';
  }
  // Wrap plain text snippet into a module
  return `// Auto-generated by compile_strategy.cjs\n`+
         `const user = {};\n`+
         `${src}\n`+
         `module.exports = {\n`+
         `  onStart: user.onStart || function(){},\n`+
         `  onStop: user.onStop || function(){},\n`+
         `  onCandle: user.onCandle || function(c){},\n`+
         `  params: user.params || { N:2, volumeFactor:0.8, atrStop:0.9, targetR:1.1, qty:100 }\n`+
         `};\n`;
}

(function main(){
  const args = process.argv.slice(2);
  let inp=null,outp=null;
  for (let i=0;i<args.length;i++){
    const a=args[i], n=args[i+1];
    if (a==='--in' || a==='--input'){ inp=n; i++; }
    else if (a==='--out'){ outp=n; i++; }
  }
  if (!inp || !outp){ usage(); process.exit(2); }
  fs.mkdirSync(path.dirname(outp), { recursive: true });
  if (outp.endsWith('.json')){
    const cfg = readJson(inp);
    if (!cfg){ console.error('ERR invalid JSON at', inp); process.exit(3); }
    const norm = normalize(cfg);
    fs.writeFileSync(outp, JSON.stringify({ strategyConfig: norm, compiledAt: new Date().toISOString() }, null, 2), 'utf8');
    console.log('OK compiled', outp);
  } else if (outp.endsWith('.js')) {
    const src = fs.readFileSync(inp, 'utf8');
    const wrapped = wrapToModule(src);
    fs.writeFileSync(outp, wrapped, 'utf8');
    console.log('OK compiled', outp);
  } else {
    console.error('ERR unknown out extension:', outp);
    process.exit(4);
  }
})();
